name: Builds

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.cpp"
      - "**.h"
      - "**/SConstruct"
      - "**/SConscript"
      - .github/workflows/builds.yaml

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
